export type UserRole = "admin" | "corporate" | "fleet" | "broker" | "insurance" | "workshop";
export type UserStatus = "pending_email" | "pending_mobile" | "pending_approval" | "approved" | "rejected" | "suspended" | "inactive";
export type Tone = "purple" | "magenta" | "green" | "amber" | "red" | "blue";

export type Metric = {
  label: string;
  value: string;
  helper: string;
  tone?: Tone;
  icon: string;
};

export type DashboardAction = {
  title: string;
  description: string;
  tone: Tone;
  icon: string;
};

export type RoleConfig = {
  value: UserRole;
  label: string;
  shortLabel: string;
  dashboardPath: string;
  company: string;
  userName: string;
  initials: string;
  location: string;
  description: string;
  sidebar: string[];
  modules: string[];
  metrics: Metric[];
  activities: { text: string; time: string; tone: Tone }[];
  actions: DashboardAction[];
};

export const roleConfigs: RoleConfig[] = [
  {
    value: "admin",
    label: "Admin",
    shortLabel: "Admin",
    dashboardPath: "/dashboard/admin",
    company: "MechPro Experts HQ",
    userName: "Admin User",
    initials: "AU",
    location: "Mumbai",
    description: "Platform operations overview",
    sidebar: ["Dashboard", "User Approvals", "Users", "Business Clients", "Service Partners", "Claims", "Reports", "Settings"],
    modules: ["Approvals", "Users", "Claims", "Partners", "Reports"],
    metrics: [
      { label: "Pending Approvals", value: "8", helper: "+3 today", tone: "magenta", icon: "👥" },
      { label: "Active Users", value: "142", helper: "+12 this week", tone: "purple", icon: "◎" },
      { label: "Active Claims", value: "56", helper: "8 critical", tone: "amber", icon: "▣" },
      { label: "Partner Workshops", value: "500+", helper: "5 new", tone: "green", icon: "🔧" },
    ],
    activities: [
      { text: "InsureWell Brokers submitted registration", time: "10 min ago", tone: "purple" },
      { text: "SpeedFix Garage approved by admin", time: "1 hr ago", tone: "green" },
      { text: "TechCorp Fleet rejected - docs incomplete", time: "3 hr ago", tone: "red" },
      { text: "Claim #C-2847 escalated by Mumbai team", time: "5 hr ago", tone: "amber" },
    ],
    actions: [
      { title: "Review Acme Corp Pvt. Ltd.", description: "Corporate - Thane", tone: "amber", icon: "◷" },
      { title: "Review InsureWell Brokers", description: "Broker - Mumbai", tone: "amber", icon: "◷" },
      { title: "View All Approvals (8)", description: "Open approvals table", tone: "purple", icon: "→" },
    ],
  },
  {
    value: "corporate",
    label: "Corporate Client",
    shortLabel: "Corporate",
    dashboardPath: "/dashboard/business",
    company: "Acme Corp Pvt. Ltd.",
    userName: "Rajesh Kumar",
    initials: "RK",
    location: "Thane",
    description: "Corporate mobility workspace",
    sidebar: ["Dashboard", "Create Request", "My Requests", "Vehicles", "Quotations", "Invoices", "Support"],
    modules: ["Create Request", "My Requests", "Vehicles", "Quotations", "Invoices"],
    metrics: [
      { label: "Open Requests", value: "7", helper: "2 urgent", tone: "purple", icon: "▤" },
      { label: "Pending Approvals", value: "3", helper: "Awaiting action", tone: "amber", icon: "◷" },
      { label: "Completed Services", value: "24", helper: "This month", tone: "green", icon: "✓" },
      { label: "Invoices Pending", value: "INR 1.2L", helper: "4 invoices", tone: "magenta", icon: "▣" },
    ],
    activities: [
      { text: "Vehicle MH-04-AB-1234 service request raised", time: "30 min ago", tone: "purple" },
      { text: "Claim #C-2801 settled - INR 48,000", time: "2 hr ago", tone: "green" },
      { text: "Quotation QT-445 awaiting your approval", time: "4 hr ago", tone: "amber" },
      { text: "Invoice INV-221 generated by workshop", time: "1 day ago", tone: "blue" },
    ],
    actions: [
      { title: "Raise New Service Request", description: "Breakdown, repair, or inspection", tone: "purple", icon: "+" },
      { title: "View Open Quotations (3)", description: "Pending your approval", tone: "amber", icon: "▣" },
      { title: "My Fleet Vehicles (45)", description: "View and manage vehicles", tone: "green", icon: "🚗" },
    ],
  },
  {
    value: "fleet",
    label: "Fleet Owner",
    shortLabel: "Fleet Owner",
    dashboardPath: "/dashboard/fleet",
    company: "TechCorp Fleet India",
    userName: "Vikram Singh",
    initials: "VS",
    location: "Panvel",
    description: "Fleet operations command center",
    sidebar: ["Dashboard", "Fleet Vehicles", "Service Jobs", "Breakdown Support", "Claims", "Payments"],
    modules: ["Fleet Vehicles", "Service Jobs", "Claims", "Payments", "Support"],
    metrics: [
      { label: "Fleet Vehicles", value: "45", helper: "3 in service", tone: "purple", icon: "🚙" },
      { label: "Jobs In Progress", value: "6", helper: "2 urgent", tone: "amber", icon: "🔧" },
      { label: "Breakdowns", value: "2", helper: "Active now", tone: "red", icon: "🚨" },
      { label: "Payments Due", value: "INR 84K", helper: "5 invoices", tone: "green", icon: "▣" },
    ],
    activities: [
      { text: "Breakdown alert - MH-04-TK-7821 Thane", time: "5 min ago", tone: "red" },
      { text: "Service job SJ-388 completed - Navi Mumbai", time: "2 hr ago", tone: "purple" },
      { text: "Invoice INV-445 received from SpeedFix", time: "4 hr ago", tone: "amber" },
      { text: "Claim #C-2788 settled - INR 32,000", time: "1 day ago", tone: "green" },
    ],
    actions: [
      { title: "Report Breakdown", description: "Emergency 2hr SLA guaranteed", tone: "red", icon: "△" },
      { title: "Raise Service Request", description: "Scheduled or priority service", tone: "purple", icon: "🔧" },
      { title: "View Fleet Vehicles (45)", description: "Status and service history", tone: "green", icon: "🚗" },
    ],
  },
  {
    value: "broker",
    label: "Insurance Broker",
    shortLabel: "Broker",
    dashboardPath: "/dashboard/broker",
    company: "InsureWell Brokers",
    userName: "Priya Sharma",
    initials: "PS",
    location: "Mumbai",
    description: "Broker claim and inspection desk",
    sidebar: ["Dashboard", "Client Requests", "Pre-Inspection", "Claims", "Documents", "Reports"],
    modules: ["Client Leads", "Pre-inspection", "Claims", "Documents", "Reports"],
    metrics: [
      { label: "Client Leads", value: "18", helper: "+5 this week", tone: "purple", icon: "👥" },
      { label: "Pre-inspections", value: "6", helper: "2 today", tone: "magenta", icon: "⌕" },
      { label: "Claims Open", value: "11", helper: "3 critical", tone: "amber", icon: "▣" },
      { label: "Docs Pending", value: "4", helper: "Action needed", tone: "green", icon: "◴" },
    ],
    activities: [
      { text: "New pre-inspection request - Honda City", time: "15 min ago", tone: "magenta" },
      { text: "Client Mehta family claim #C-2849 filed", time: "1 hr ago", tone: "purple" },
      { text: "Survey follow-up completed - Panvel", time: "3 hr ago", tone: "green" },
      { text: "Document missing for claim #C-2831", time: "6 hr ago", tone: "amber" },
    ],
    actions: [
      { title: "Initiate Pre-inspection", description: "Book certified assessor", tone: "purple", icon: "⌕" },
      { title: "File New Claim", description: "Submit client claim details", tone: "magenta", icon: "+" },
      { title: "Upload Documents", description: "4 pending submissions", tone: "amber", icon: "⇧" },
    ],
  },
  {
    value: "insurance",
    label: "Insurance Company",
    shortLabel: "Insurance Co.",
    dashboardPath: "/dashboard/insurance",
    company: "HDFC ERGO General",
    userName: "Sunita Mehta",
    initials: "SM",
    location: "Mumbai",
    description: "Claims and inspection workspace",
    sidebar: ["Dashboard", "Claim Leads", "Inspection Cases", "Survey Follow-up", "Settlement Tracking", "Reports"],
    modules: ["Claim Leads", "Inspection", "Survey Follow-up", "Settlements", "Reports"],
    metrics: [
      { label: "Open Claims", value: "34", helper: "6 critical", tone: "magenta", icon: "▣" },
      { label: "Inspection Pending", value: "12", helper: "3 today", tone: "purple", icon: "⌕" },
      { label: "Survey Follow-ups", value: "8", helper: "2 overdue", tone: "amber", icon: "♙" },
      { label: "Settlements Done", value: "89", helper: "This month", tone: "green", icon: "✓" },
    ],
    activities: [
      { text: "Claim #C-2849 inspection requested - Mumbai", time: "20 min ago", tone: "magenta" },
      { text: "Survey completed for claim #C-2831", time: "1 hr ago", tone: "purple" },
      { text: "Settlement approved - INR 48,000 - Thane", time: "3 hr ago", tone: "green" },
      { text: "Surveyor follow-up pending for #C-2803", time: "8 hr ago", tone: "amber" },
    ],
    actions: [
      { title: "New Claim Inspection", description: "Assign certified inspector", tone: "purple", icon: "⌕" },
      { title: "Pending Survey Follow-ups (8)", description: "Action required", tone: "amber", icon: "◷" },
      { title: "Settlement Tracker", description: "Track all active settlements", tone: "green", icon: "◎" },
    ],
  },
  {
    value: "workshop",
    label: "Workshop / Service Provider",
    shortLabel: "Workshop",
    dashboardPath: "/dashboard/workshop",
    company: "SpeedFix Garage",
    userName: "Arun Joshi",
    initials: "AJ",
    location: "Navi Mumbai",
    description: "Workshop job operations",
    sidebar: ["Dashboard", "Assigned Jobs", "Quotations", "Job Updates", "Invoices", "Payments", "Profile"],
    modules: ["Assigned Jobs", "Quotations", "Job Updates", "Invoices", "Payments"],
    metrics: [
      { label: "Assigned Jobs", value: "9", helper: "3 new today", tone: "purple", icon: "▤" },
      { label: "Quotations Pending", value: "4", helper: "Awaiting approval", tone: "amber", icon: "▣" },
      { label: "Jobs In Progress", value: "5", helper: "Active now", tone: "magenta", icon: "🔧" },
      { label: "Payments Due", value: "INR 1.4L", helper: "3 invoices", tone: "green", icon: "▣" },
    ],
    activities: [
      { text: "New job assigned - Honda City repair", time: "10 min ago", tone: "purple" },
      { text: "Job SJ-377 completed - Toyota Innova", time: "2 hr ago", tone: "green" },
      { text: "Quotation QT-445 awaiting client approval", time: "4 hr ago", tone: "amber" },
      { text: "Payment received - INV-220 - INR 38,500", time: "1 day ago", tone: "blue" },
    ],
    actions: [
      { title: "Update Job Status", description: "Mark progress on assigned jobs", tone: "purple", icon: "↻" },
      { title: "Submit Quotation", description: "Upload repair quote to client", tone: "green", icon: "▣" },
      { title: "Raise Invoice (3 ready)", description: "Complete and send invoices", tone: "amber", icon: "▤" },
    ],
  },
];

export const businessTypes = ["Corporate", "Insurance Broker", "Insurance Company", "Fleet Owner", "Workshop / Service Provider"];
export const cities = ["Mumbai", "Thane", "Navi Mumbai", "Panvel", "Palghar"];
export const vehicleRanges = ["1 - 10", "11 - 50", "51 - 200", "200+"];

export const userStatuses = [
  "Pending Email Verification",
  "Pending Mobile Verification",
  "Pending Admin Approval",
  "Approved",
  "Rejected",
  "Suspended",
  "Inactive",
];

export const approvalUsers = [
  { company: "Acme Corp Pvt. Ltd.", contact: "Rajesh Kumar", role: "Corporate", city: "Thane", email: "Verified", mobile: "Verified", docs: "3 uploaded", status: "Pending", submitted: "22 May 2026" },
  { company: "InsureWell Brokers", contact: "Priya Sharma", role: "Broker", city: "Mumbai", email: "Verified", mobile: "Pending", docs: "1 uploaded", status: "Pending", submitted: "21 May 2026" },
  { company: "SpeedFix Garage", contact: "Arun Joshi", role: "Workshop", city: "Navi Mumbai", email: "Verified", mobile: "Verified", docs: "5 uploaded", status: "Approved", submitted: "20 May 2026" },
  { company: "TechCorp Fleet India", contact: "Vikram Singh", role: "Fleet Owner", city: "Panvel", email: "Verified", mobile: "Verified", docs: "Incomplete", status: "Rejected", submitted: "19 May 2026" },
  { company: "HDFC ERGO General", contact: "Sunita Mehta", role: "Insurance Co.", city: "Mumbai", email: "Verified", mobile: "Verified", docs: "4 uploaded", status: "Suspended", submitted: "18 May 2026" },
];

export function getRoleConfig(role: UserRole) {
  return roleConfigs.find((config) => config.value === role) ?? roleConfigs[1];
}
