import type { UserRole } from '@/types';

export interface MetricItem {
  label: string;
  value: string;
  sub: string;
  accent: string;
  icon: string;
}

export interface ActivityItem {
  dot: string;
  text: string;
  time: string;
}

export interface QuickAction {
  label: string;
  sub: string;
  accent: string;
  bg: string;
  href: string;
}

export interface SidebarNavItem {
  label: string;
  icon: string;
  href: string;
  badge?: number;
}

export interface DashboardData {
  role: UserRole;
  userName: string;
  userInitials: string;
  userCompany: string;
  userCity: string;
  greeting: string;
  metrics: MetricItem[];
  activity: ActivityItem[];
  quickActions: QuickAction[];
  navItems: SidebarNavItem[];
}

export const DASHBOARD_DATA: Record<UserRole, DashboardData> = {
  admin: {
    role: 'admin',
    userName: 'Admin User',
    userInitials: 'AU',
    userCompany: 'MechPro Experts',
    userCity: 'Mumbai',
    greeting: 'Platform Overview',
    metrics: [
      { label: 'Pending Approvals', value: '8',    sub: '+3 today',          accent: '#EC4899', icon: '⏳' },
      { label: 'Active Users',      value: '142',  sub: '+12 this week',     accent: '#7C3AED', icon: '👥' },
      { label: 'Active Claims',     value: '56',   sub: '8 critical',        accent: '#F59E0B', icon: '📋' },
      { label: 'Partner Workshops', value: '500+', sub: '5 new this month',  accent: '#10B981', icon: '🔧' },
    ],
    activity: [
      { dot: '#7C3AED', text: 'InsureWell Brokers submitted registration',     time: '10m ago' },
      { dot: '#10B981', text: 'SpeedFix Garage — Navi Mumbai approved',        time: '1h ago'  },
      { dot: '#EF4444', text: 'MetroFleet rejected — incomplete documents',    time: '3h ago'  },
      { dot: '#F59E0B', text: 'Claim #C-2847 escalated by Mumbai team',        time: '5h ago'  },
      { dot: '#6366F1', text: 'New workshop partner registered in Thane',      time: '8h ago'  },
    ],
    quickActions: [
      { label: 'Review Acme Corp Pvt. Ltd.',   sub: 'Corporate · Thane',   accent: '#7C3AED', bg: '#1a1040', href: '#' },
      { label: 'Review InsureWell Brokers',    sub: 'Broker · Mumbai',     accent: '#EC4899', bg: '#2a0d1f', href: '#' },
      { label: 'View All Approvals (8)',        sub: 'Open queue',          accent: '#10B981', bg: '#0d2420', href: '#' },
      { label: 'Generate Monthly Report',      sub: 'May 2026',            accent: '#F59E0B', bg: '#2a1a00', href: '#' },
    ],
    navItems: [
      { label: 'Dashboard',        icon: '⊞',  href: '/dashboard/admin' },
      { label: 'User Approvals',   icon: '✓',  href: '#', badge: 8 },
      { label: 'Users',            icon: '👥', href: '#' },
      { label: 'Business Clients', icon: '🏢', href: '#' },
      { label: 'Service Partners', icon: '🔧', href: '#' },
      { label: 'Claims',           icon: '📋', href: '#' },
      { label: 'Reports',          icon: '📊', href: '#' },
      { label: 'Settings',         icon: '⚙',  href: '#' },
    ],
  },

  corporate: {
    role: 'corporate',
    userName: 'Rajesh Kumar',
    userInitials: 'RK',
    userCompany: 'Acme Corp Pvt. Ltd.',
    userCity: 'Thane',
    greeting: 'Corporate Operations',
    metrics: [
      { label: 'Open Requests',      value: '7',      sub: '2 urgent',         accent: '#EC4899', icon: '📝' },
      { label: 'Pending Approvals',  value: '3',      sub: 'Awaiting review',  accent: '#F59E0B', icon: '⏳' },
      { label: 'Completed Services', value: '24',     sub: 'This month',       accent: '#10B981', icon: '✅' },
      { label: 'Invoices Pending',   value: '₹1.2L',  sub: '4 invoices',       accent: '#7C3AED', icon: '🧾' },
    ],
    activity: [
      { dot: '#7C3AED', text: 'Vehicle MH-04-AB-1234 service request raised',   time: '30m ago' },
      { dot: '#10B981', text: 'Claim #C-2801 settled — ₹48,000',                time: '2h ago'  },
      { dot: '#F59E0B', text: 'Quotation QT-445 awaiting your approval',        time: '4h ago'  },
      { dot: '#6366F1', text: 'Invoice INV-221 generated by SpeedFix',          time: '1d ago'  },
    ],
    quickActions: [
      { label: 'Raise New Service Request', sub: 'Breakdown or repair',     accent: '#7C3AED', bg: '#1a1040', href: '#' },
      { label: 'View Open Quotations (3)',  sub: 'Pending your approval',   accent: '#F59E0B', bg: '#2a1a00', href: '#' },
      { label: 'My Fleet Vehicles (45)',    sub: 'Manage vehicles',         accent: '#10B981', bg: '#0d2420', href: '#' },
      { label: 'Download Invoice INV-221', sub: 'Ready to download',        accent: '#EC4899', bg: '#2a0d1f', href: '#' },
    ],
    navItems: [
      { label: 'Dashboard',       icon: '⊞',  href: '/dashboard/business' },
      { label: 'Create Request',  icon: '+',   href: '#' },
      { label: 'My Requests',     icon: '📝', href: '#' },
      { label: 'Vehicles',        icon: '🚗', href: '#' },
      { label: 'Quotations',      icon: '🧾', href: '#' },
      { label: 'Invoices',        icon: '📄', href: '#' },
      { label: 'Support',         icon: '🎧', href: '#' },
    ],
  },

  broker: {
    role: 'broker',
    userName: 'Priya Sharma',
    userInitials: 'PS',
    userCompany: 'SecurePolicy Brokers',
    userCity: 'Mumbai',
    greeting: 'Broker Operations',
    metrics: [
      { label: 'Client Leads',    value: '18', sub: '+5 this week',     accent: '#7C3AED', icon: '👥' },
      { label: 'Pre-inspections', value: '6',  sub: '2 today',          accent: '#EC4899', icon: '🔍' },
      { label: 'Claims Open',     value: '11', sub: '3 critical',       accent: '#F59E0B', icon: '📋' },
      { label: 'Docs Pending',    value: '4',  sub: 'Action needed',    accent: '#EF4444', icon: '📁' },
    ],
    activity: [
      { dot: '#EC4899', text: 'Pre-inspection request — Honda City, Panvel',    time: '15m ago' },
      { dot: '#7C3AED', text: 'Client Mehta family claim #C-2849 filed',        time: '1h ago'  },
      { dot: '#10B981', text: 'Survey follow-up completed — Panvel office',     time: '3h ago'  },
      { dot: '#F59E0B', text: 'Document missing for claim #C-2831',             time: '6h ago'  },
    ],
    quickActions: [
      { label: 'Initiate Pre-inspection',    sub: 'Book certified assessor',   accent: '#7C3AED', bg: '#1a1040', href: '#' },
      { label: 'File New Claim',             sub: 'Submit client details',     accent: '#EC4899', bg: '#2a0d1f', href: '#' },
      { label: 'Upload Pending Docs (4)',    sub: 'Action required',           accent: '#F59E0B', bg: '#2a1a00', href: '#' },
      { label: 'View Client Reports',        sub: 'May 2026 summary',          accent: '#10B981', bg: '#0d2420', href: '#' },
    ],
    navItems: [
      { label: 'Dashboard',       icon: '⊞',  href: '/dashboard/broker' },
      { label: 'Client Requests', icon: '👥', href: '#' },
      { label: 'Pre-inspection',  icon: '🔍', href: '#' },
      { label: 'Claims',          icon: '📋', href: '#' },
      { label: 'Documents',       icon: '📁', href: '#' },
      { label: 'Reports',         icon: '📊', href: '#' },
    ],
  },

  fleet: {
    role: 'fleet',
    userName: 'Vikram Singh',
    userInitials: 'VS',
    userCompany: 'MetroFleet Logistics',
    userCity: 'Panvel',
    greeting: 'Fleet Management',
    metrics: [
      { label: 'Fleet Vehicles',   value: '45',     sub: '3 in service',      accent: '#7C3AED', icon: '🚗' },
      { label: 'Jobs In Progress', value: '6',      sub: '2 urgent',          accent: '#F59E0B', icon: '🔧' },
      { label: 'Breakdowns',       value: '2',      sub: 'Active alerts',     accent: '#EF4444', icon: '🚨' },
      { label: 'Payments Due',     value: '₹84K',   sub: '5 invoices',        accent: '#10B981', icon: '💳' },
    ],
    activity: [
      { dot: '#EF4444', text: 'Breakdown alert — MH-04-TK-7821, Thane NH',     time: '5m ago'  },
      { dot: '#7C3AED', text: 'Service job SJ-388 completed — Navi Mumbai',     time: '2h ago'  },
      { dot: '#F59E0B', text: 'Invoice INV-445 received from SpeedFix',         time: '4h ago'  },
      { dot: '#10B981', text: 'Claim #C-2788 settled — ₹32,000',               time: '1d ago'  },
    ],
    quickActions: [
      { label: 'Report Breakdown',           sub: '2hr SLA guaranteed',        accent: '#EF4444', bg: '#2a0d0d', href: '#' },
      { label: 'Raise Service Request',      sub: 'Scheduled or priority',     accent: '#7C3AED', bg: '#1a1040', href: '#' },
      { label: 'Fleet Vehicles (45)',        sub: 'Status and history',        accent: '#10B981', bg: '#0d2420', href: '#' },
      { label: 'Pay Invoices (₹84K due)',    sub: '5 pending',                 accent: '#F59E0B', bg: '#2a1a00', href: '#' },
    ],
    navItems: [
      { label: 'Dashboard',          icon: '⊞',  href: '/dashboard/fleet' },
      { label: 'Fleet Vehicles',     icon: '🚗', href: '#' },
      { label: 'Service Jobs',       icon: '🔧', href: '#' },
      { label: 'Breakdown Support',  icon: '🚨', href: '#' },
      { label: 'Claims',             icon: '📋', href: '#' },
      { label: 'Payments',           icon: '💳', href: '#' },
    ],
  },

  insurance: {
    role: 'insurance',
    userName: 'Sunita Mehta',
    userInitials: 'SM',
    userCompany: 'Urban Claims Desk',
    userCity: 'Mumbai',
    greeting: 'Insurance Operations',
    metrics: [
      { label: 'Open Claims',          value: '34', sub: '6 critical',         accent: '#EC4899', icon: '📋' },
      { label: 'Inspection Pending',   value: '12', sub: '3 today',            accent: '#7C3AED', icon: '🔍' },
      { label: 'Survey Follow-ups',    value: '8',  sub: '2 overdue',          accent: '#F59E0B', icon: '👤' },
      { label: 'Settlements Done',     value: '89', sub: 'This month',         accent: '#10B981', icon: '✅' },
    ],
    activity: [
      { dot: '#EC4899', text: 'Claim #C-2849 inspection requested — Mumbai',    time: '20m ago' },
      { dot: '#7C3AED', text: 'Survey completed for claim #C-2831',             time: '1h ago'  },
      { dot: '#10B981', text: 'Settlement approved — ₹48,000 — Thane',         time: '3h ago'  },
      { dot: '#F59E0B', text: 'Surveyor follow-up pending for #C-2803',        time: '8h ago'  },
    ],
    quickActions: [
      { label: 'Assign Inspection',          sub: 'Claim #C-2849',            accent: '#7C3AED', bg: '#1a1040', href: '#' },
      { label: 'Survey Follow-ups (8)',      sub: 'Action required',          accent: '#F59E0B', bg: '#2a1a00', href: '#' },
      { label: 'Settlement Tracker',         sub: 'Active settlements',       accent: '#10B981', bg: '#0d2420', href: '#' },
      { label: 'Generate Claims Report',     sub: 'May 2026',                 accent: '#EC4899', bg: '#2a0d1f', href: '#' },
    ],
    navItems: [
      { label: 'Dashboard',            icon: '⊞',  href: '/dashboard/insurance' },
      { label: 'Claim Leads',          icon: '📋', href: '#' },
      { label: 'Inspection Cases',     icon: '🔍', href: '#' },
      { label: 'Survey Follow-up',     icon: '👤', href: '#' },
      { label: 'Settlement Tracking',  icon: '💰', href: '#' },
      { label: 'Reports',              icon: '📊', href: '#' },
    ],
  },

  workshop: {
    role: 'workshop',
    userName: 'Arun Joshi',
    userInitials: 'AJ',
    userCompany: 'Mumbai AutoCare Partners',
    userCity: 'Navi Mumbai',
    greeting: 'Workshop Operations',
    metrics: [
      { label: 'Assigned Jobs',       value: '9',     sub: '3 new today',      accent: '#7C3AED', icon: '🔧' },
      { label: 'Quotations Pending',  value: '4',     sub: 'Awaiting approval', accent: '#F59E0B', icon: '🧾' },
      { label: 'Jobs In Progress',    value: '5',     sub: 'Active now',        accent: '#EC4899', icon: '⚙' },
      { label: 'Payments Due',        value: '₹1.4L', sub: '3 invoices',        accent: '#10B981', icon: '💳' },
    ],
    activity: [
      { dot: '#7C3AED', text: 'New job assigned — Honda City 1.5L petrol',      time: '10m ago' },
      { dot: '#10B981', text: 'Job SJ-377 completed — Toyota Innova Crysta',    time: '2h ago'  },
      { dot: '#F59E0B', text: 'Quotation QT-445 awaiting client approval',      time: '4h ago'  },
      { dot: '#6366F1', text: 'Payment received INV-220 — ₹38,500',            time: '1d ago'  },
    ],
    quickActions: [
      { label: 'Update Job Status',        sub: 'Mark progress',              accent: '#7C3AED', bg: '#1a1040', href: '#' },
      { label: 'Submit Quotation',         sub: 'Upload repair quote',        accent: '#10B981', bg: '#0d2420', href: '#' },
      { label: 'Raise Invoice (3 ready)',  sub: 'Send to clients',            accent: '#F59E0B', bg: '#2a1a00', href: '#' },
      { label: 'View Assigned Jobs (9)',   sub: 'All active jobs',            accent: '#EC4899', bg: '#2a0d1f', href: '#' },
    ],
    navItems: [
      { label: 'Dashboard',      icon: '⊞',  href: '/dashboard/workshop' },
      { label: 'Assigned Jobs',  icon: '📝', href: '#' },
      { label: 'Quotations',     icon: '🧾', href: '#' },
      { label: 'Job Updates',    icon: '🔄', href: '#' },
      { label: 'Invoices',       icon: '📄', href: '#' },
      { label: 'Payments',       icon: '💳', href: '#' },
      { label: 'Profile',        icon: '👤', href: '#' },
    ],
  },
};

export const ROLE_LABELS: Record<UserRole, string> = {
  admin:     'Admin',
  corporate: 'Corporate Client',
  fleet:     'Fleet Owner',
  broker:    'Insurance Broker',
  insurance: 'Insurance Company',
  workshop:  'Workshop Partner',
};

export const ROLE_BADGE_STYLES: Record<UserRole, { bg: string; text: string }> = {
  admin:     { bg: '#3b1f80', text: '#c4b5fd' },
  corporate: { bg: '#1f2d80', text: '#93c5fd' },
  fleet:     { bg: '#064e3b', text: '#6ee7b7' },
  broker:    { bg: '#831843', text: '#f9a8d4' },
  insurance: { bg: '#78350f', text: '#fde68a' },
  workshop:  { bg: '#0c4a6e', text: '#bae6fd' },
};
